import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const readJson = (path) => JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'))

test('service work scheduler release freezes strategy while bounding proxy work', () => {
  const manifest = readJson('../../release/v105-service-work-scheduler-release-manifest.json')
  assert.equal(manifest.releaseName, 'v105影子序列Hydration修正版1')
  assert.equal(manifest.releaseVersion, 'v105-shadow-hydration-serial.1')
  assert.equal(manifest.gitTag, 'v105-shadow-hydration-serial.1')
  assert.equal(manifest.applicationVersion, '1.0.24')
  assert.equal(manifest.strategyVersion, 'v105')
  assert.equal(manifest.protocolVersion, 'v105')
  assert.equal(manifest.databaseMigrationRequired, false)
  assert.equal(manifest.behavior.formalSettlementConcurrency, 1)
  assert.equal(manifest.behavior.serviceWorkConcurrency, 1)
  assert.equal(manifest.behavior.shadowWorkConcurrency, 1)
  assert.equal(manifest.behavior.formalAckWaitsForShadow, false)
  assert.equal(manifest.behavior.retainFinalBehindTimedOutShadowWork, true)
  assert.equal(manifest.behavior.priorityBurstLimit, 4)
  assert.equal(manifest.behavior.shadowServiceWorkTimeoutMs, 2000)
  assert.equal(manifest.behavior.shadowShutdownDeadlineMs, 5000)
  assert.equal(manifest.behavior.outboxCompletionWaitsForShadowDrain, true)
  assert.equal(manifest.behavior.permanentHangRetainedByDurableOutbox, true)
  assert.equal(manifest.behavior.shadowIsolation, 'child_process_fork')
  assert.equal(manifest.behavior.oneIpcBatchPerOutboxLease, true)
  assert.equal(manifest.behavior.killChildOnTimeoutOrAbort, true)
  assert.equal(manifest.behavior.secretsOverIpc, false)
  assert.equal(manifest.behavior.childEnvironmentAllowlist, true)
  assert.equal(manifest.behavior.exactLeaseAbsoluteDeadlineFence, true)
  assert.equal(manifest.behavior.childExitConfirmedBeforeLeaseFailure, true)
  assert.equal(manifest.behavior.formalEnrichedTablesSentToChild, true)
  assert.equal(manifest.behavior.formalRankLedgerBatchHydration, true)
  assert.equal(manifest.behavior.formalSnapshotFifo, true)
  assert.equal(manifest.behavior.underlyingLeasePhaseSettledBeforeFailureAck, true)
  assert.equal(manifest.behavior.failureAckAttempts, 1)
  assert.equal(manifest.behavior.unconfirmedChildTermination, 'fatal_process_exit_70')
  assert.equal(manifest.behavior.hydrationBeforeOutboxClaim, true)
  assert.equal(manifest.behavior.hydrationConcurrency, 'enabled_runtimes')
  assert.equal(manifest.behavior.captureConcurrency, 'per_item_across_runtimes')
  assert.equal(manifest.behavior.shadowCrossTableConcurrency, 'bounded_by_table_identity')
  assert.equal(manifest.behavior.shadowMaxConcurrentRuntimeOperations, 9)
  assert.equal(manifest.behavior.shadowSameTablePayloadOrder, 'sequential')
  assert.equal(manifest.behavior.outboxWorkDeadlineMs, 45000)
  assert.equal(manifest.behavior.shadowHydrationReadiness, 'per_runtime')
  assert.equal(manifest.behavior.shadowHydrationPendingSingleFlight, true)
  assert.equal(manifest.behavior.shadowHydrationFailureObservedBeforeRetry, true)
  assert.equal(manifest.behavior.shadowCaptureRequiresAllEnabledRuntimesReady, true)
  assert.equal(manifest.behavior.shadowPartialWritesBeforeReady, false)
  assert.equal(manifest.behavior.shadowHistoryRequestTimeoutPropagated, true)
  assert.equal(manifest.behavior.shutdownStopsChildBeforeOutboxWait, true)
  assert.equal(manifest.behavior.shadowHydrationConcurrency, 1)
  assert.equal(manifest.behavior.shadowHydrationRetryOrder, 'fifo_tail')
  assert.deepEqual(manifest.behavior.shadowReadinessRequiredFields, ['enabled', 'prepared', 'pending', 'queued', 'failed'])
  assert.equal(manifest.behavior.shadowReadinessCountConsistent, true)
  assert.equal(manifest.behavior.outboxClaimRequiresAllShadowReady, true)
  assert.equal(manifest.behavior.shadowReadinessPollingDoesNotConsumeAttempt, true)
  assert.equal(manifest.behavior.failureAckAttemptedOnce, true)
  assert.equal(manifest.behavior.exactNoIssuanceOnly, true)
  assert.equal(manifest.behavior.schedulerRejectsAfterClosing, true)
  assert.equal(manifest.behavior.staleIssuanceReconcilesLatest, true)
  assert.equal(manifest.behavior.coalesceLatestTableObservation, true)
  assert.equal(manifest.behavior.waitForServiceWorkOnShutdown, true)
  assert.equal(manifest.behavior.rejectStaleScreenIssuance, true)
  assert.equal(manifest.behavior.predictionRulesChanged, false)
  assert.equal(manifest.behavior.predictionWeightsChanged, false)
  assert.equal(manifest.behavior.settlementSemanticsChanged, false)
  assert.deepEqual(manifest.deploymentOrder, [
    'proxy-render-exact-commit',
    'outbox-live-drain',
    'watchdog-health-readback',
    'live-five-minute-e2e',
  ])
  assert.equal(manifest.rollback.targetTag, 'v1.0.23')
  assert.equal(manifest.rollback.preserveQueueCursorJournal, true)
  assert.equal(manifest.rollback.preserveOutboxHistory, true)
})

test('all deployable packages use application version 1.0.24', () => {
  for (const path of ['../package.json', '../../frontend/package.json', '../../cloud-browser-worker/package.json']) {
    assert.equal(readJson(path).version, '1.0.24')
  }
})
